### ISSUE TITLE
Can you share rest ppt of Dynamic memory ?

### ISSUE THREAD

**Issue by GarrickLin** [mtrebi/memory-allocators#11]
Thank you for sharing your code and ppt for `Dynamic memory`. There is only part 1 of your `Dynamic memory` tutorials and it is really nice to read and to learn. If it is possible, can you share the rest of the docs ! Thank you very much !

**Comment by mtrebi** [comment]
Hey,

I couldn't find the finished version of that ppt. I've only found a draft including the main points that were discussed in the that presentation. which was only a summary of the readme of the repository (with some images and jokes). You aren't really missing anything, trust me. If you have any question, feel free to ask me. Sorry about that.

Mariano.

**Comment by GarrickLin** [comment]
Sorry for late reply ! Thank you very much ! I've read your readme carefully and learned a lot ! Thanks again !
