### ISSUE TITLE
Can't compile the code. 

### ISSUE THREAD

**Issue by MaxISoP** [mtrebi/memory-allocators#3]
First of all thanks for such a good example and comparison of how memory allocator works. 

Sadly, after I followed the instruction and compiled it in VS, compiler told me I can't use "void* address [m_nOperations]" since m_nOperations is not a constant. How did you get it work?

**Comment by MaxISoP** [comment]
gzito's fork refractored for VS on Windows.

**Comment by mtrebi** [comment]
Hey! Sorry I did the project on Linux and later I added the instructions to generate the project files with CMake. I didn´t take into account differences in the compilers and system libraries. I'll fix it whenever I have some free time. But, as you said, Gzito seems to be doing a good job ;)

**Comment by MaxISoP** [comment]
@mtrebi I can compile the code successfully now thanks to Gzito's version :P! Are you going to write Red Black tree version at some point?
