### ISSUE TITLE
Potential infinite loop caused by linked list node pointing to itself

### ISSUE THREAD

**Issue by urosidoki** [mtrebi/memory-allocators#9]
Hi,

****Deleted*****

I was actually wrong! :)

Cheers,
Jose

**Comment by urosidoki** [comment]
I also notices something in this code:
```
    if (rest > 0) {
        // We have to split the block into the data block and a free block of size 'rest'
        Node * newFreeNode = (Node *)((std::size_t) affectedNode + requiredSize);
        newFreeNode->data.blockSize = rest;
        m_freeList.insert(affectedNode, newFreeNode);
    }
```
After doing some allocation and deallocation, that newNode might point to some piece of memory that can contains random data because it was used before. So, the newFreeNode->next will be pointing to random memory address, am I right? that seems like a problem to me.

**Comment by urosidoki** [comment]
Sorry! There is no issue at all!

**Comment by mtrebi** [comment]
👍
